# Generated by Django 2.2.6 on 2020-01-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nome Completo')),
                ('date_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=150, verbose_name='Sexo')),
                ('color', models.CharField(max_length=150, verbose_name='Cor')),
                ('marital_state', models.CharField(choices=[('Solteiro (a)', 'Solteiro (a)'), ('Casado (a)', 'Casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viúvo (a)', 'Viúvo (a)')], max_length=150, verbose_name='Estado Conjugal')),
                ('ocupation', models.CharField(max_length=150, verbose_name='Ocupação')),
                ('local_birth', models.CharField(max_length=150, verbose_name='Local de Nascimento')),
                ('health_insurance', models.CharField(max_length=150, verbose_name='Convênio')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=150, verbose_name='Telefone')),
                ('fax', models.CharField(max_length=150, verbose_name='fax')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_on'],
            },
        ),
    ]
