# Generated by Django 2.2.6 on 2020-02-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address_numero',
        ),
        migrations.AddField(
            model_name='patient',
            name='address_number',
            field=models.CharField(default='S/N', max_length=6, verbose_name='Número do Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_cep',
            field=models.CharField(default='64600000', max_length=8, verbose_name='Cep do Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_neighborhood',
            field=models.CharField(max_length=45, verbose_name='Bairro do Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpf_patient',
            field=models.CharField(max_length=100, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='N/A', max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image_patient',
            field=models.ImageField(blank=True, null=True, upload_to='patient/image', verbose_name='Imagem do paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('CELL', 'CELL'), ('RESIDENCIAL', 'RESIDENCIAL'), ('COMERCIAL', 'COMERCIAL'), ('FAX', 'FAX')], default='CELL', max_length=11, verbose_name='Tipo de telefone'),
        ),
    ]
