# Generated by Django 2.2.6 on 2020-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf_patient',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
