# Generated by Django 2.2.6 on 2020-02-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='city_cod',
            new_name='City_codIBGE',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='color_id',
            new_name='Color_idColor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='marital_state_id',
            new_name='Marital_State_idMarital_State',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medical_Insurance_id',
            new_name='Medical_Insurance_idMedical_insurance',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='ocupation_id',
            new_name='Ocupation_idOcupation',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='type_Logradouro_id',
            new_name='Type_Logradouro_idLogradouro',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='patient_id',
            new_name='Patient_idPatient',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='State_codIBGE_UF',
        ),
        migrations.AddField(
            model_name='patient',
            name='image_patient',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Número de telefone'),
        ),
    ]
