# Generated by Django 2.2.6 on 2020-02-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200221_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='codIBGE7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código IBGE7'),
        ),
        migrations.AlterField(
            model_name='state',
            name='region',
            field=models.CharField(default=1, max_length=25, verbose_name='Região'),
            preserve_default=False,
        ),
    ]
