# Generated by Django 2.2.6 on 2020-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200311_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_cep',
            field=models.CharField(max_length=8, verbose_name='Cep do Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_number',
            field=models.CharField(max_length=6, verbose_name='Número do Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number_main',
            field=models.CharField(max_length=16, unique=True, verbose_name='Número de telefone (principal)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number_optional',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Número de telefone (opcional)'),
        ),
    ]
