# Generated by Django 2.2.6 on 2020-02-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200205_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='port',
            field=models.CharField(max_length=20, verbose_name='Porte'),
        ),
    ]
