# Generated by Django 2.2.6 on 2020-02-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200131_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image_patient',
            field=models.ImageField(blank=True, null=True, upload_to='patient/<django.db.models.fields.CharField>'),
        ),
    ]
