# Generated by Django 2.2.6 on 2020-02-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200205_1816'),
        ('patient', '0003_auto_20200205_2216'),
    ]

    operations = [
    ]
