# Generated by Django 2.2.6 on 2022-06-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200312_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number_optional',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_type_optional',
        ),
    ]
