# Generated by Django 2.2.6 on 2020-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200131_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image_patient',
            field=models.ImageField(blank=True, null=True, upload_to='patient/<function Patient.get_cpf at 0x7f217803ca60>'),
        ),
    ]
