# Generated by Django 2.2.6 on 2022-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20220626_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cep do Endereço'),
        ),
    ]
