# Generated by Django 2.2.6 on 2020-01-22 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nome Completo')),
                ('date_birth', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=150, verbose_name='Sexo')),
                ('color', models.CharField(max_length=150, verbose_name='Cor')),
                ('marital_state', models.CharField(blank=True, choices=[('Solteiro (a)', 'Solteiro (a)'), ('Casado (a)', 'Casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viúvo (a)', 'Viúvo (a)')], max_length=150, verbose_name='Estado Conjugal')),
                ('ocupation', models.CharField(max_length=150, verbose_name='Ocupação')),
                ('local_birth', models.CharField(max_length=150, verbose_name='Local de Nascimento')),
                ('health_insurance', models.CharField(max_length=150, verbose_name='Convênio')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Telefone')),
                ('fax', models.CharField(max_length=150, verbose_name='fax')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('pa', models.CharField(max_length=50, verbose_name='PA')),
                ('p', models.CharField(max_length=50, verbose_name='P')),
                ('fc', models.TextField(max_length=50, verbose_name='FC')),
                ('epidemiological_history', models.CharField(max_length=50, verbose_name='FR')),
                ('previous_pathological_history', models.CharField(max_length=50, verbose_name='TAX')),
                ('family_history', models.CharField(max_length=50, verbose_name='Peso')),
                ('physiological_personal_antecedents', models.CharField(max_length=50, verbose_name='Altura')),
            ],
            options={
                'verbose_name': 'Exame Fisico',
                'verbose_name_plural': 'Exames Fisicos',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MedicalQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('main_complaint', models.CharField(max_length=400, verbose_name='Queixa Principal')),
                ('current_health_history', models.CharField(max_length=400, verbose_name='Queixa Principal')),
                ('review_of_systems', models.TextField(max_length=400, verbose_name='Revisão de Sistemas')),
                ('epidemiological_history', models.CharField(max_length=400, verbose_name='História Epidemiológica')),
                ('previous_pathological_history', models.CharField(max_length=400, verbose_name='História Patológica Regressa')),
                ('family_history', models.CharField(max_length=400, verbose_name='História Familiar')),
                ('physiological_personal_antecedents', models.CharField(max_length=400, verbose_name='Antecedentes Pessoais Fisiológicas')),
                ('summary', models.CharField(max_length=400, verbose_name='Sumário dos Postos Principais da História e Exame Físico')),
                ('Diagnostic_hypotheses', models.CharField(max_length=400, verbose_name='Hipótese(s) Diagnósticada(s)')),
                ('take_duct', models.CharField(max_length=400, verbose_name='Conduta Tomada')),
                ('medical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Patient', verbose_name='Paciente')),
                ('physical_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.PhysicalExam', verbose_name='Exame Físico')),
            ],
            options={
                'verbose_name': 'Consulta Medica',
                'verbose_name_plural': 'Consultas Medicas',
                'ordering': ['-created_on'],
            },
        ),
    ]
