# Generated by Django 2.2.6 on 2020-02-03 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_query',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 18, 3, 47, 84340, tzinfo=utc), verbose_name='Data'),
        ),
    ]
