# Generated by Django 2.2.6 on 2020-01-25 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 22, 1, 12, 736478, tzinfo=utc), verbose_name='Data'),
        ),
    ]
