# Generated by Django 2.2.6 on 2020-02-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date_query',
        ),
        migrations.AlterField(
            model_name='query',
            name='User_idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='query',
            name='type_query',
            field=models.IntegerField(choices=[(1, 'Consulta'), (2, 'Retorno')], verbose_name='Tipo de Consulta'),
        ),
    ]
