# Generated by Django 2.2.6 on 2020-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_has_Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='Autalizado em')),
                ('amount', models.IntegerField(verbose_name='Tipo de Consulta')),
                ('Medicine_idMedicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Medicine', verbose_name='Medicamento')),
                ('Query_idQuery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Query', verbose_name='Consulta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
