# Generated by Django 2.2.6 on 2020-02-22 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor', verbose_name='Profissional'),
        ),
    ]
