# Generated by Django 2.2.6 on 2020-02-01 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_query',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 21, 26, 24, 275132, tzinfo=utc), verbose_name='Data'),
        ),
    ]
