# Generated by Django 2.2.6 on 2020-01-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_state',
            field=models.CharField(choices=[('Solteiro (a)', 'Solteiro (a)'), ('Casado (a)', 'Casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viúvo (a)', 'Viúvo (a)')], max_length=150, verbose_name='Estado Conjugal'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Telefone'),
        ),
    ]
