# Generated by Django 2.2.6 on 2020-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequest',
            name='desc_exam',
            field=models.TextField(max_length=255, verbose_name='Descrição do exame'),
        ),
    ]
