# Generated by Django 2.2.6 on 2020-02-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200203_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phisicalexam',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='phisicalexam',
            name='weigth',
        ),
    ]
