# Generated by Django 2.2.6 on 2020-02-01 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200201_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_query',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 21, 31, 10, 158932, tzinfo=utc), verbose_name='Data'),
        ),
    ]
