# Generated by Django 2.2.6 on 2020-03-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200309_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrequest',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='examrequest',
            name='updated_on',
        ),
    ]
