# Generated by Django 2.2.6 on 2020-01-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200124_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Endereço'),
        ),
    ]
