# Generated by Django 2.2.6 on 2020-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200221_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['created_on'], 'verbose_name': 'Consulta Medica', 'verbose_name_plural': 'Consultas Medicas'},
        ),
        migrations.AddField(
            model_name='forwarding',
            name='in_attendance',
            field=models.BooleanField(default=False, verbose_name='Paciente em atendimento'),
        ),
    ]
