# Generated by Django 2.2.6 on 2020-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_query_has_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_has_medicine',
            name='amount',
            field=models.CharField(max_length=400, verbose_name='Quantidade'),
        ),
    ]
