# Generated by Django 2.2.6 on 2020-02-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200227_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Patient_idPatient',
        ),
    ]
