# Generated by Django 2.2.6 on 2020-02-04 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0002_auto_20200203_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_query',
            field=models.DateField(default=datetime.datetime(2020, 2, 4, 1, 45, 56, 762479, tzinfo=utc), verbose_name='Data'),
        ),
    ]
