# Generated by Django 2.2.6 on 2020-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0003_auto_20200303_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_has_medicine',
            name='Medicine_idMedicine',
        ),
        migrations.AddField(
            model_name='query_has_medicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Medicine', verbose_name=' Medicamento'),
        ),
    ]
