# Generated by Django 2.2.6 on 2020-02-01 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0003_auto_20200201_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_query',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 21, 33, 3, 760139, tzinfo=utc), verbose_name='Data'),
        ),
    ]
