# Generated by Django 2.2.6 on 2020-01-26 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0003_auto_20200126_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalquery',
            name='fr',
            field=models.CharField(default=1, max_length=50, verbose_name='FR(irpm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalquery',
            name='hidth',
            field=models.CharField(default=1, max_length=50, verbose_name='Altura(cm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalquery',
            name='peso',
            field=models.CharField(default=1, max_length=50, verbose_name='Peso(g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalquery',
            name='tax',
            field=models.CharField(default=1, max_length=50, verbose_name='TAX(ºC)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 15, 31, 59, 889221, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='epidemiological_history',
            field=models.CharField(max_length=400, verbose_name='História Epidemiológica'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='family_history',
            field=models.CharField(max_length=400, verbose_name='História Familiar'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='physiological_personal_antecedents',
            field=models.CharField(max_length=400, verbose_name='Antecedentes Pessoais Fisiológicas'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='previous_pathological_history',
            field=models.CharField(max_length=400, verbose_name='História Patológica Regressa'),
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('pa', models.CharField(max_length=50, verbose_name='PA(mmHg)')),
                ('p', models.CharField(max_length=50, verbose_name='P(bpm)')),
                ('fc', models.CharField(max_length=50, verbose_name='FC(bpm)')),
                ('epidemiological_history', models.CharField(max_length=50, verbose_name='FR(irpm)')),
                ('previous_pathological_history', models.CharField(max_length=50, verbose_name='TAX(ºC)')),
                ('family_history', models.CharField(max_length=50, verbose_name='Peso(g)')),
                ('physiological_personal_antecedents', models.CharField(max_length=50, verbose_name='Altura(cm)')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.MedicalQuery', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Exame Fisico',
                'verbose_name_plural': 'Exames Fisicos',
                'ordering': ['-created_on'],
            },
        ),
    ]
