# Generated by Django 2.2.6 on 2020-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0003_auto_20200222_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequest',
            name='desc_exam',
            field=models.CharField(max_length=255, verbose_name='Descrição do exame'),
        ),
        migrations.AlterField(
            model_name='phisicalexam',
            name='heigth',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Altura(cm)'),
        ),
        migrations.AlterField(
            model_name='phisicalexam',
            name='weigth',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Peso'),
        ),
    ]
