# Generated by Django 2.2.6 on 2021-10-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0003_auto_20200309_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cid10',
            name='desc_CID10',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
    ]
