# Generated by Django 2.2.6 on 2020-02-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('medical_query', '0003_remove_query_patient_idpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Patient_idPatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient', verbose_name='Paciente'),
        ),
    ]
