# Generated by Django 2.2.6 on 2020-01-26 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_auto_20200126_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalquery',
            old_name='hidth',
            new_name='heigth',
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 15, 33, 11, 746260, tzinfo=utc), verbose_name='Data'),
        ),
    ]
