# Generated by Django 2.2.6 on 2020-02-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_auto_20200203_1935'),
        ('medical_query', '0003_auto_20200203_2245'),
    ]

    operations = [
    ]
