# Generated by Django 2.2.6 on 2022-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_auto_20211023_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='identification',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Identificação'),
        ),
        migrations.AddField(
            model_name='query',
            name='responsible_academics',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Acadêmicos Responsáveis'),
        ),
        migrations.AddField(
            model_name='query',
            name='specific_physical_exam',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Exame físico específico'),
        ),
        migrations.AddField(
            model_name='query',
            name='staff_CRM',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Staff + CRM'),
        ),
        migrations.AlterField(
            model_name='query',
            name='previous_pathological_history',
            field=models.TextField(max_length=400, verbose_name='Historia Patologia Pregressa'),
        ),
    ]
