# Generated by Django 2.2.6 on 2020-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_query_patient_idpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryhasexamrequest',
            name='ExamRequest_idExam',
        ),
        migrations.RemoveField(
            model_name='queryhasexamrequest',
            name='Query_idQuery_EXAM',
        ),
        migrations.RemoveField(
            model_name='queryhasmedicine',
            name='Medicine_idMedicine',
        ),
        migrations.RemoveField(
            model_name='queryhasmedicine',
            name='Query_idQuery_MEDICINE',
        ),
        migrations.AddField(
            model_name='query',
            name='cid10',
            field=models.ManyToManyField(to='medical_query.CID10', verbose_name='CID10'),
        ),
        migrations.AddField(
            model_name='query',
            name='examRequest',
            field=models.ManyToManyField(to='medical_query.ExamRequest', verbose_name='Exame(s)'),
        ),
        migrations.AddField(
            model_name='query',
            name='medicine',
            field=models.ManyToManyField(to='medical_query.Medicine', verbose_name='Medicamento(s)'),
        ),
        migrations.DeleteModel(
            name='QueryHasCID10',
        ),
        migrations.DeleteModel(
            name='QueryHasExamRequest',
        ),
        migrations.DeleteModel(
            name='QueryHasMedicine',
        ),
    ]
