# Generated by Django 2.2.6 on 2020-03-04 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_auto_20200303_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHasMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='Autalizado em')),
                ('amount', models.CharField(max_length=400, null=True, verbose_name='Quantidade')),
                ('Query_idQuery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Query', verbose_name='Consulta')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_query.Medicine', verbose_name=' Medicamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Query_has_Medicine',
        ),
    ]
