# Generated by Django 2.2.6 on 2020-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0004_auto_20200303_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarding',
            name='finalized',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='query_has_medicine',
            name='amount',
            field=models.CharField(max_length=400, null=True, verbose_name='Quantidade'),
        ),
    ]
