# Generated by Django 2.2.6 on 2020-01-26 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0005_auto_20200126_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalquery',
            old_name='fc',
            new_name='fc_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='fr',
            new_name='fr_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='heigth',
            new_name='heigth_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='p',
            new_name='p_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='pa',
            new_name='pa_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='peso',
            new_name='peso_exam',
        ),
        migrations.RenameField(
            model_name='medicalquery',
            old_name='tax',
            new_name='tax_exam',
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 15, 38, 20, 296134, tzinfo=utc), verbose_name='Data'),
        ),
    ]
