# Generated by Django 2.2.6 on 2020-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0005_auto_20200304_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='gestational_history',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='História Gestacional'),
        ),
        migrations.AddField(
            model_name='query',
            name='repoductive_health',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Saúde Repodutiva'),
        ),
    ]
