# Generated by Django 2.2.6 on 2022-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0005_auto_20220626_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='summary',
            field=models.TextField(max_length=400, verbose_name='Lista de problemas'),
        ),
    ]
