# Generated by Django 2.2.6 on 2020-02-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0005_auto_20200228_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='cid10',
            field=models.ManyToManyField(related_name='cid10', to='medical_query.CID10', verbose_name='CID10'),
        ),
        migrations.AlterField(
            model_name='query',
            name='current_health_history',
            field=models.TextField(max_length=400, verbose_name='História da Doença Atual'),
        ),
        migrations.AlterField(
            model_name='query',
            name='diagnostic_hypotheses',
            field=models.TextField(max_length=400, verbose_name='Hipótese(s) Diagnósticada(s)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='epidemiological_history',
            field=models.TextField(max_length=400, verbose_name='História Epidemiológica'),
        ),
        migrations.AlterField(
            model_name='query',
            name='examRequest',
            field=models.ManyToManyField(related_name='examRequest', to='medical_query.ExamRequest', verbose_name='Exame(s)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='family_history',
            field=models.TextField(max_length=400, verbose_name='História Familiar'),
        ),
        migrations.AlterField(
            model_name='query',
            name='main_complaint',
            field=models.TextField(max_length=400, verbose_name='Queixa Principal'),
        ),
        migrations.AlterField(
            model_name='query',
            name='medicine',
            field=models.ManyToManyField(related_name='medicine', to='medical_query.Medicine', verbose_name='Medicamento(s)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='physiological_personal_antecedents',
            field=models.TextField(max_length=400, verbose_name='Antecedentes Pessoais Fisiológicas'),
        ),
        migrations.AlterField(
            model_name='query',
            name='previous_pathological_history',
            field=models.TextField(max_length=400, verbose_name='História Patológica Regressa'),
        ),
        migrations.AlterField(
            model_name='query',
            name='summary',
            field=models.TextField(max_length=400, verbose_name='Sumário dos Postos Principais da História e Exame Físico'),
        ),
        migrations.AlterField(
            model_name='query',
            name='take_duct',
            field=models.TextField(max_length=400, verbose_name='Conduta Tomada'),
        ),
    ]
