# Generated by Django 2.2.6 on 2020-02-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0006_auto_20200229_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarding',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Paciente Prioritário'),
        ),
    ]
