# Generated by Django 2.2.6 on 2020-01-26 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0006_auto_20200126_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalquery',
            old_name='Diagnostic_hypotheses',
            new_name='diagnostic_hypotheses',
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 18, 51, 49, 353833, tzinfo=utc), verbose_name='Data'),
        ),
    ]
