# Generated by Django 2.2.6 on 2020-03-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0006_auto_20200304_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='User_idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='query',
            name='repoductive_health',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Saúde Reprodutiva'),
        ),
    ]
