# Generated by Django 2.2.6 on 2020-01-26 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0007_auto_20200126_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalquery',
            name='opened',
            field=models.BooleanField(default=True, verbose_name='Consulta em Aberto'),
        ),
        migrations.AddField(
            model_name='medicalquery',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Paciente Prioritário'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 19, 24, 58, 307705, tzinfo=utc), verbose_name='Data'),
        ),
    ]
