# Generated by Django 2.2.6 on 2020-01-30 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0009_auto_20200126_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 19, 15, 16, 247652, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='medicalquery',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient', verbose_name='Paciente'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
