# Generated by Django 2.2.6 on 2020-01-30 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0010_auto_20200130_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 19, 17, 9, 144901, tzinfo=utc), verbose_name='Data'),
        ),
    ]
