# Generated by Django 2.2.6 on 2020-01-30 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0011_auto_20200130_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 30, 20, 6, 39, 634190, tzinfo=utc), verbose_name='Data'),
        ),
    ]
