# Generated by Django 2.2.6 on 2020-01-31 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0012_auto_20200130_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 14, 36, 30, 624955, tzinfo=utc), verbose_name='Data'),
        ),
    ]
