# Generated by Django 2.2.6 on 2020-01-31 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0014_auto_20200131_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 31, 19, 2, 19, 204218, tzinfo=utc), verbose_name='Data'),
        ),
    ]
