# Generated by Django 2.2.6 on 2020-02-01 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0015_auto_20200131_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 2, 23, 52, 76877, tzinfo=utc), verbose_name='Data'),
        ),
    ]
