# Generated by Django 2.2.6 on 2020-02-01 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0016_auto_20200131_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 2, 42, 58, 615816, tzinfo=utc), verbose_name='Data'),
        ),
    ]
