# Generated by Django 2.2.6 on 2020-02-01 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0017_auto_20200131_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquery',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 18, 43, 56, 622197, tzinfo=utc), verbose_name='Data'),
        ),
    ]
