# Generated by Django 2.2.6 on 2020-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0002_doctorhasmedicalspecialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorhasmedicalspecialty',
            name='doctor',
            field=models.ManyToManyField(to='accounts.Doctor', verbose_name='Especialidade'),
        ),
    ]
