# Generated by Django 2.2.6 on 2020-02-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200205_1943'),
        ('specialty', '0003_auto_20200205_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalspecialty',
            options={'verbose_name': 'Especialidade Médica', 'verbose_name_plural': 'Especialidades Médicas'},
        ),
        migrations.RemoveField(
            model_name='doctorhasmedicalspecialty',
            name='MedicalSpecialty_idSpecialty',
        ),
        migrations.AddField(
            model_name='doctorhasmedicalspecialty',
            name='MedicalSpecialty_idSpecialty',
            field=models.ManyToManyField(to='specialty.MedicalSpecialty', verbose_name='Especialidade'),
        ),
        migrations.RemoveField(
            model_name='doctorhasmedicalspecialty',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorhasmedicalspecialty',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor', verbose_name='Médico'),
        ),
    ]
