# Generated by Django 2.2.6 on 2020-02-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0003_auto_20200205_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalspecialty',
            options={'verbose_name': 'Especialidade Médica', 'verbose_name_plural': 'Especialidades Médicas'},
        ),
        migrations.AlterField(
            model_name='doctorhasmedicalspecialty',
            name='doctor',
            field=models.ManyToManyField(to='accounts.Doctor', verbose_name='Médico'),
        ),
    ]
