# Generated by Django 2.2.6 on 2020-02-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=1, verbose_name='is staff'),
            preserve_default=False,
        ),
    ]
