# Generated by Django 2.2.6 on 2020-02-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(blank=True, choices=[('1', 'Admin'), ('2', 'Médico(a)'), ('3', 'Atendente')], null=True, verbose_name='Tipo de usuário'),
        ),
    ]
