# Generated by Django 2.2.6 on 2020-02-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_clerk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clerk',
            field=models.BooleanField(default=False, verbose_name='Atendente'),
        ),
    ]
