# Generated by Django 2.2.6 on 2020-02-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200201_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo')], null=True, verbose_name='Status do usuário'),
        ),
    ]
