# Generated by Django 2.2.6 on 2021-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200312_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='register_clerk',
            field=models.CharField(max_length=12, verbose_name='registro do técnico'),
        ),
    ]
