# Generated by Django 2.2.6 on 2020-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200204_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_clerk',
            field=models.BooleanField(default=False, verbose_name='Atendente'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Medico'),
        ),
    ]
