# Generated by Django 2.2.6 on 2020-02-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200204_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='CRM_doc',
            new_name='crm_doc',
        ),
    ]
