# Generated by Django 2.2.6 on 2022-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210316_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM do médico'),
        ),
    ]
