# Generated by Django 2.2.6 on 2020-02-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_query', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_auto_20200204_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorHasMedicalSpecialty',
        ),
        migrations.DeleteModel(
            name='MedicalSpecialty',
        ),
    ]
